import { CDN_URL } from "./const";

export const assets = {
  clientProjects: {
    amriel: {
      aboutImage: `${CDN_URL}/client-projects/amriel-about.png`,
      createImage: `${CDN_URL}/client-projects/amriel-create.png`,
      freeImage: `${CDN_URL}/client-projects/amriel-free.png`,
      galleryImage: `${CDN_URL}/client-projects/amriel-gallery.png`,
      homeImage: `${CDN_URL}/client-projects/amriel-home.png`,
      homeVideo: `${CDN_URL}/client-projects/amriel-home.mp4`,
      productImage: `${CDN_URL}/client-projects/amriel-product.png`,
      productsImage: `${CDN_URL}/client-projects/amriel-products.png`,
    },
    awaken: {
      aboutTextImage: `${CDN_URL}/client-projects/awaken-about-text.png`,
      aboutImage: `${CDN_URL}/client-projects/awaken-about.png`,
      contactImage: `${CDN_URL}/client-projects/awaken-contact.png`,
      game1Image: `${CDN_URL}/client-projects/awaken-game-1.png`,
      game2Image: `${CDN_URL}/client-projects/awaken-game-2.png`,
      game3Image: `${CDN_URL}/client-projects/awaken-game-3.png`,
      game4Image: `${CDN_URL}/client-projects/awaken-game-4.png`,
      gameEnterImage: `${CDN_URL}/client-projects/awaken-game-enter.png`,
      homeImage: `${CDN_URL}/client-projects/awaken-home.png`,
      homeVideo: `${CDN_URL}/client-projects/awaken-home.mp4`,
    },
    chalkheads: {
      bootImage: `${CDN_URL}/client-projects/chalkheads-boot.png`,
      bootVideo: `${CDN_URL}/client-projects/chalkheads-boot.mp4`,
      browseImage: `${CDN_URL}/client-projects/chalkheads-browse.png`,
      homeImage: `${CDN_URL}/client-projects/chalkheads-home.png`,
      preview1Image: `${CDN_URL}/client-projects/chalkheads-preview-1.png`,
      preview2Image: `${CDN_URL}/client-projects/chalkheads-preview-2.png`,
      preview3Image: `${CDN_URL}/client-projects/chalkheads-preview-3.png`,
      watchImage: `${CDN_URL}/client-projects/chalkheads-watch.png`,
    },
    comunal: {
      homeImage: `${CDN_URL}/client-projects/comunal-home.png`,
      menuImage: `${CDN_URL}/client-projects/comunal-menu.png`,
      privacyImage: `${CDN_URL}/client-projects/comunal-privacy.png`,
      termsImage: `${CDN_URL}/client-projects/comunal-terms.png`,
    },
    mokk: {
      homeVideo: `${CDN_URL}/client-projects/mokk-home.mp4`,
      home1Image: `${CDN_URL}/client-projects/mokk-home-1.png`,
      home2Image: `${CDN_URL}/client-projects/mokk-home-2.png`,
      home3Image: `${CDN_URL}/client-projects/mokk-home-3.png`,
    },
    wins: {
      codesSectionImage: `${CDN_URL}/client-projects/wins-codes-section.png`,
      homeImage: `${CDN_URL}/client-projects/wins-home.png`,
      homeVideo: `${CDN_URL}/client-projects/wins-home.mp4`,
      missionSectionImage: `${CDN_URL}/client-projects/wins-mission-section.png`,
      photoGridImage: `${CDN_URL}/client-projects/wins-photo-grid.png`,
      productImage: `${CDN_URL}/client-projects/wins-product.png`,
      sizeChartImage: `${CDN_URL}/client-projects/wins-size-chart.png`,
      teaserGridImage: `${CDN_URL}/client-projects/wins-teaser-grid.png`,
    },
  },
};
